### ISSUE TITLE
Import error with coverage

### ISSUE THREAD

**Issue by aschn** [jpadilla/django-dotenv#11]
I have a file `tmp.py` that imports dotenv, and I've pip-installed django-dotenv==1.3.0 and coverage==3.7.1. When I run the file as a script, it works just fine. But when I run it with coverage, an `ImportError` is raised:

```
$ coverage run tmp.py 
Traceback (most recent call last):
  File "tmp.py", line 1, in <module>
    import dotenv
ImportError: No module named dotenv
```

FYI I discovered this when running `coverage run manage.py test` using this [Django template](https://github.com/jpadilla/django-project-template). Any thoughts?

**Comment by mroswell** [comment]
Same thing happened with me. In my case, I needed to be in the virtual environment on the virtual machine. This command solved my particular instance of the same ImportError:
```
../ve/bin/python manage.py shell
```
In any case, make sure you're in the same environment where Django is running.

**Comment by amitkm9204** [comment]
facing problem in stepping forward....
PS C:\Users\AMIT\git\pontoon> python manage.py migrate
Traceback (most recent call last):
  File "manage.py", line 6, in <module>
    import dotenv
ImportError: No module named dotenv
