### ISSUE TITLE
documentation request: .env

### ISSUE THREAD

**Issue by mroswell** [jpadilla/django-dotenv#13]
Can you provide an example of what to put in the .env file?

**Comment by mroswell** [comment]
I found some good parallel documentation here: https://devcenter.heroku.com/articles/config-vars
So, I can see the likely structure of the .env file, along with a reminder to add .env to .gitignore

**Comment by jpadilla** [comment]
Closed by 3687e1b124653f8b77b4b76d6558feb8b8715d62. Reference to [tests.py](https://github.com/jpadilla/django-dotenv/blob/master/tests.py) to see all supported formats.

**Comment by merwok** [comment]
Thanks for this!  It helped me choose django-dotenv over alternatives because of the support for bash-compatible files.  Would be nice to have some examples in the README though.

**Comment by jpadilla** [comment]
@merwok PRs are welcome :)
