### ISSUE TITLE
Use dotenv with Gunicorn

### ISSUE THREAD

**Issue by edwinlunando** [jpadilla/django-dotenv#14]
When I put the 
```python
import dotenv
dotenv.read_dotenv()
```
on `manage.py` it runs ok, but when I wan to use Gunicorn to production and put it in `wsgi.py`, it did not read the `.env` file. Any idea?

**Comment by jpadilla** [comment]
`read_dotenv()` accepts an optional path to a file. You could do something like:

```python
dotenv.read_dotenv(os.path.join(os.path.dirname(os.path.dirname(__file__)), '.env'))
```

**Comment by edwinlunando** [comment]
It works! But why it didn't worked on the first time? I think if it do not find any `.env` it will backtrack to its parent directory.
