### ISSUE TITLE
Is there a reason not to override variables

### ISSUE THREAD

**Issue by mochawich** [jpadilla/django-dotenv#20]
I noticed you are using `os.environ.setdefault(k, v)` which means if there is an already populated key in the current environment it will be ignored. Was this intended?

Thanks

**Comment by jpadilla** [comment]
Not sure if this was intended or not. What's the current behavior in other similar packages like:

- https://github.com/bkeepers/dotenv
- https://www.npmjs.com/package/dotenv

**Comment by tremby** [comment]
In other dotenv packages I've used (PHP and nodejs), variables in the environment are absolutely not overridden by whatever is in a .env file.

**Comment by mochawich** [comment]
Thank you guys, I just didn't use env dot files before and therefore didn't know whether this was the right approach or not.
