### ISSUE TITLE
Doc's Issue--virtual env incorrect

### ISSUE THREAD

**Issue by lotusgraham** [jpadilla/django-dotenv#21]
The docs specify to run a different name of virtual env than you create.

![screen shot 2016-08-09 at 6 54 07 pm](https://cloud.githubusercontent.com/assets/13974084/17536401/b988cac2-5e62-11e6-8e9e-8e1d56f96e03.png)

**Comment by jpadilla** [comment]
@lotusgraham seems like you accidentally created an issue on this repo, but are referring to another one.
