### ISSUE TITLE
Integrate with `django-admin`?

### ISSUE THREAD

**Issue by chadsaun** [jpadilla/django-dotenv#24]
Any good ideas out there to get this to work with the `django-admin` command?

**Comment by merwok** [comment]
Not sure what the question is.  Do you mean that you want django-admin startproject to somehow generate a settings file that uses dotenv?  That’s probably out of scope for django core, and I don’t know of any hooks that would let dotenv change code.  I think many people use things like cookiecutter, or just copy settings from one project to the next.

**Comment by chadsaun** [comment]
Sorry, what I meant was is there a way to load the environment variables when using `django-admin` command.  The other way is to just use `manage.py`, but in my case I've setup my CLI aliases to use `django-admin`.

**Comment by chadsaun** [comment]
Ah yes, makes sense 👍
