### ISSUE TITLE
Use default value if variable not defined in .env

### ISSUE THREAD

**Issue by anuj9196** [jpadilla/django-dotenv#36]
Is there a way to pass an optional value to use if the variable does not exist in the `.env` file?

For example, say I have the following content in `.env` file
```
DEBUG=False
```

And in `settings.py` file, I have
```
DEBUG=os.environ.get('DEBUG')
```
I want to set `DEBUG` in settings.py file to `False` if the variable is not defined in the `.env` file.

**Comment by ebridges** [comment]
Perhaps I'm missing an aspect of your use case, but maybe you just do this in `settings.py`:

```
DEBUG=os.environ.get('DEBUG', False)
```
